Gourav Verma<br>
DSC 650<br>
Assignment 10.1.c : Create a vector

In [1]:
import string
import nltk
from numpy import array
from numpy import argmax
from keras.utils import to_categorical

In [2]:
def onehtencode(data):
    data = array(data)
    print("Received array")
    print(data)
    # one hot encode
    encoded = to_categorical(data)
    return encoded

In [3]:
data = [1, 3, 2, 0, 3, 2, 2, 1, 0, 1]
encodedval = onehtencode(data)
print("One Hot Encoded values")
print(encodedval)

Received array
[1 3 2 0 3 2 2 1 0 1]
One Hot Encoded values
[[0. 1. 0. 0.]
 [0. 0. 0. 1.]
 [0. 0. 1. 0.]
 [1. 0. 0. 0.]
 [0. 0. 0. 1.]
 [0. 0. 1. 0.]
 [0. 0. 1. 0.]
 [0. 1. 0. 0.]
 [1. 0. 0. 0.]
 [0. 1. 0. 0.]]
